# Generated by Django 5.0.2 on 2024-02-11 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('octanaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tiposangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreVehiculo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCircuito', models.CharField(max_length=100)),
                ('nombreParroquia', models.CharField(max_length=100)),
                ('iddependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='subCircuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSubCircuito', models.CharField(max_length=100)),
                ('idCircuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.circuito')),
            ],
        ),
        migrations.CreateModel(
            name='personaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('idrango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.rango')),
                ('idsubCircuito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.subcircuito')),
                ('idtiposangre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.tiposangre')),
            ],
        ),
        migrations.CreateModel(
            name='vehiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chasis', models.CharField(max_length=50, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20)),
                ('motor', models.CharField(max_length=100, null=True)),
                ('kilometraje', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cilindraje', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('capacidad_pasajeros', models.PositiveIntegerField(null=True)),
                ('idsubCircuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.subcircuito')),
                ('idtipoCombustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipocombustible')),
                ('idtipoVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipovehiculo')),
            ],
        ),
    ]
