# Generated by Django 5.0.2 on 2024-02-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('idvehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculomodel')),
                ('idtipomantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.tipomantenimiento')),
            ],
        ),
    ]
