# Generated by Django 5.0 on 2024-01-14 02:18
from django.db import migrations, models
tipos_sangre = [
    {"nombre": f"Tipo {tipo}{orh}"}
    for tipo in ["A", "B", "AB", "O"]
    for orh in ["+", "-"]
]


def adelante(apps, schema_editor):
    tiposangre = apps.get_model("principal", "tiposangre")
    for sangre in tipos_sangre:
        tiposangre.objects.get_or_create(**sangre)


def atras(apps, schema_editor):
    tiposangre = apps.get_model("principal", "tiposangre")
    for sangre in tipos_sangre:
        try:
            tipo = tiposangre.objects.get(**sangre)
            tipo.delete()
        except models.Model.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_tipomantenimiento_mantenimiento'),
    ]

    operations = [
        migrations.RunPython(adelante, reverse_code=atras)
    ]
