# Generated by Django 5.0 on 2024-01-14 05:01

from django.db import migrations, models
tipo_rango = [
    {"nombre": f"{tipo} {subtipo}"}
    for tipo in ["Capitan", "Teniente", "Subteniente", "Sargento", "Cabo"]
    for subtipo in ["Primero", "Segundo"]
]


def arriba(apps, schema_editor):
    tiporango = apps.get_model("principal", "rango")
    for rango in tipo_rango:
        tiporango.objects.get_or_create(**rango)


def atras(apps, schema_editor):
    tiporango = apps.get_model("principal", "rango")
    for rango in tipo_rango:
        try:
            tipo = tiporango.objects.get(**rango)
            tipo.delete()
        except models.Model.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_tiposangre'),
    ]

    operations = [
        migrations.RunPython(arriba, reverse_code=atras)
    ]
