# Generated by Django 5.0 on 2024-01-14 05:01

from django.db import migrations, models
tipo_vehiculo = [
    {"nombreVehiculo": f"{tipo}"}
    for tipo in ["Automóvil", "Camión", "Autobús"]
]


def arriba(apps, schema_editor):
    tvehiculo = apps.get_model("principal", "tipoVehiculo")
    for tipoVehiculo in tipo_vehiculo:
        tvehiculo.objects.get_or_create(**tipoVehiculo)


def atras(apps, schema_editor):
    tvehiculo = apps.get_model("principal", "tipoVehiculo")
    for tipoVehiculo in tipo_vehiculo:
        try:
            tipo = tvehiculo.objects.get(**tipoVehiculo)
            tipo.delete()
        except models.Model.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_rango'),
    ]

    operations = [
        migrations.RunPython(arriba, reverse_code=atras)
    ]
