# Generated by Django 5.0 on 2024-01-14 05:01

from django.db import migrations, models
tipo_combustible = [
    {"nombre":f"{combustible}", "octanaje": 95}
    for combustible in ["Gasolina", "diesel", "Super"]
]


def arriba(apps, schema_editor):
    tcombustible = apps.get_model("principal", "tipoCombustible")
    for tipoCombustible in tipo_combustible:
        tcombustible.objects.get_or_create(**tipoCombustible)


def atras(apps, schema_editor):
    tcombustible = apps.get_model("principal", "tipoCombustible")
    for tipoCombustible in tipo_combustible:
        try:
            tipo = tcombustible.objects.get(**tipoCombustible)
            tipo.delete()
        except models.Model.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_tipovehiculo'),
    ]

    operations = [
        migrations.RunPython(arriba, reverse_code=atras)
    ]
