# Generated by Django 5.0 on 2024-01-14 05:01

from django.db import migrations, models
tipo_mantenimiento = [
    {"nombre":f"{tipo}"}
    for tipo in ["Mantenimiento 1", "Manteimiento 2", " Mantenimiento 3"]
]


def arriba(apps, schema_editor):
    tmantenimiento = apps.get_model("principal", "tipoMantenimiento")
    for tipoMantenimiento in tipo_mantenimiento:
        tmantenimiento.objects.get_or_create(**tipoMantenimiento)


def atras(apps, schema_editor):
    tmantenimiento = apps.get_model("principal", "tipoMantenimiento")
    for tipoMantenimiento in tipo_mantenimiento:
        try:
            tipo = tmantenimiento.objects.get(**tipoMantenimiento)
            tipo.delete()
        except models.Model.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_tipocombustible'),
    ]

    operations = [
        migrations.RunPython(arriba, reverse_code=atras)
    ]
