# Generated by Django 5.0.2 on 2024-02-17 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_personamodel_idtipovehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personamodel',
            name='idtipoVehiculo',
        ),
        migrations.AddField(
            model_name='personamodel',
            name='vehiculo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculomodel'),
        ),
    ]
