# Generated by Django 5.0.2 on 2024-02-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0011_remove_personamodel_idtipovehiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudmovilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(null=True)),
                ('fecha_salida', models.DateField(null=True)),
                ('hora_salida', models.DateTimeField(null=True)),
                ('ruta', models.TextField(null=True)),
                ('kilometraje_inicio', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
