# Generated by Django 5.0.2 on 2024-02-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_solicitudmovilizacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solicitudmovilizacion',
            new_name='SMovilizacionModel',
        ),
    ]
