# Generated by Django 5.0.2 on 2024-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0014_rename_smovilizacionmodel_movilizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movilizacion',
            name='hora_salida',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
