# Generated by Django 5.0.2 on 2024-02-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_alter_movilizacion_hora_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='movilizacion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.personamodel'),
        ),
    ]
