# Generated by Django 5.0.2 on 2024-02-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0016_movilizacion_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movilizacion',
            name='persona',
        ),
    ]
