# Generated by Django 5.0.2 on 2024-02-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_remove_movilizacion_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='movilizacion',
            name='ocupantes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movilizacion',
            name='personaModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.personamodel'),
        ),
        migrations.AddField(
            model_name='movilizacion',
            name='vehiculo_marca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movilizacion',
            name='vehiculo_placa',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
