# Generated by Django 5.0.2 on 2024-02-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_movilizacion_ocupantes_movilizacion_personamodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movilizacion',
            name='vehiculo_marca',
        ),
        migrations.RemoveField(
            model_name='movilizacion',
            name='vehiculo_placa',
        ),
        migrations.AddField(
            model_name='movilizacion',
            name='vehiculoModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.vehiculomodel'),
        ),
    ]
