# Generated by Django 5.0.2 on 2024-02-23 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_remove_movilizacion_vehiculo_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasolinera', models.CharField(max_length=100)),
                ('galones_combustible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField()),
                ('kilometraje_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_solicitud', models.DateField()),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible_conductor', to='principal.personamodel')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible_solicitante', to='principal.personamodel')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible_vehiculo', to='principal.vehiculomodel')),
            ],
        ),
    ]
