# Generated by Django 5.0.2 on 2024-02-23 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_remove_registrocombustible_fecha_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroCombustible',
        ),
    ]
