# Generated by Django 5.0.2 on 2024-02-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_alter_registrocombustible_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pistola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_arma', models.CharField(max_length=100)),
                ('nombre_arma', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(max_length=20)),
                ('dependencia_rastriillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.dependencia')),
            ],
        ),
    ]
