# Generated by Django 5.0.2 on 2024-02-23 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_pistola'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perchero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personal', models.CharField(max_length=100)),
                ('apellido_personal', models.CharField(max_length=100)),
                ('rango_personal', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=8)),
                ('cedula_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.personamodel')),
                ('tipo_arma_asignada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.pistola')),
            ],
        ),
    ]
